# Generated by Django 3.2.25 on 2024-11-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('department', models.CharField(choices=[('HR', 'HR'), ('Engineering', 'Engineering'), ('Sales', 'Sales'), ('Accounts', 'Accounts')], default=None, max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Analyst', 'Analyst'), ('Customer Executive', 'Customer Executive')], default=None, max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
